### ISSUE TITLE
Nexus 5 not recognized

### ISSUE THREAD

**Issue by nohappiness** [Tasssadar/multirom#106]
I have a second-hand nexus 5 for some other stuff, and recently I've found this multirom thing which looks so amazing to me and wanna have a try.
But when I've downloaded the apk (which should be able to work on nexus 5 without problems), it just showed me that "this is a unsupported device(board)!"
Is there some other apps or a specific version of roms I need to install/flash on the device ? I've currently using a 4.4 rom ( I've already forget where I get this rom, but if it's necessary I'll do a rom-flash on this nexus 5).

Thanks

**Comment by z3ntu** [comment]
This should go to https://github.com/Tasssadar/MultiROMMgr, but no idea why that happens.

**Comment by nohappiness** [comment]
Well, I've re-flashed the rom to CM-11 and now it could be recognized. Issue closed.
Thanks.
