### ISSUE TITLE
Is encryption possible 

### ISSUE THREAD

**Issue by ghost** [Tasssadar/multirom#37]
just wondering if its possible to still encrypt your phone, or would have to encrypt a small partion for you secondary rom?

**Comment by patcon** [comment]
Did you end up getting an answer on this @Zaxscdvf?

**Comment by patcon** [comment]
Heh. OK, I think I got my answer here, which presumably you did too:
https://github.com/Tasssadar/multirom/issues/10

**Comment by Zaxscdvf** [comment]
ya found it there, sad to see that's its not that realistic to do..
