### ISSUE TITLE
MultiRom Ubuntu touch not booting up

### ISSUE THREAD

**Issue by RonCan** [Tasssadar/multirom#52]
Here's my MultiRom Log http://pastebin.com/Z7PtkUZd I tried both stable and dev versions. This log is from the Dev version, after the Google screen it said error occurred and log has been generated. If I try the stable version of Ubuntu touch it never goes ahead of Google screen

**Comment by nikwen** [comment]
People keep reporting that on XDA. The Ubuntu installation method seems to be broken.

http://forum.xda-developers.com/nexus-4/general/rom-ubuntu-touch-14-10-utopic-unico-t2324683/post59987505#post59987505

**Comment by mkotsbak** [comment]
This seems to still be valid.

**Comment by haroondilshad** [comment]
The solution for me was trying different versions of UbuntuTouch from the app, most of them didn't work. The versioning needs to be understood, once I understood the version labelling, I quickly was up and running. Closing
