### ISSUE TITLE
Compilation error after freetype 2.6.0 merge

### ISSUE THREAD

**Issue by kotzir** [Tasssadar/multirom#68]
make: **\* No rule to make target `external/freetype//src/base/ftxf86.c', needed by`/home/kostoulhs/cm12.1/out/target/product/loganreltexx/obj/STATIC_LIBRARIES/libft2_mrom_static_intermediates/src/base/ftxf86.o'.  Stop.
make: **\* Waiting for unfinished jobs....

**Comment by petr-stety-stetka** [comment]
I have same problem :(

**Comment by kostoulhs** [comment]
I have fixed it by reverting the 2.6.0 freetype update

**Comment by omerjerk** [comment]
Cherry-pick this commit to fix the error - https://github.com/omerjerk/multirom/commit/4811ff3305f5885ad23eba83cc4c518a45f4904f

**Comment by petr-stety-stetka** [comment]
Thank you @omerjerk it is working :)
