### ISSUE TITLE
Huawei Nexus 6P (anger) - Error while booting any secondary ROM

### ISSUE THREAD

**Issue by bilbaodigital** [Tasssadar/multirom#94]
![img_2906](https://cloud.githubusercontent.com/assets/19414260/15333208/0e8b85aa-1c69-11e6-9aff-2d0141395915.JPG)
![img_2907](https://cloud.githubusercontent.com/assets/19414260/15333218/19f1aeec-1c69-11e6-9ea1-78ce51736f53.JPG)
Hello, I know this is an unsupported device. This error appears when booting with any secondary ROM. The primary ROM works flawlessly. Following the error info I reported this to the developer :-).
I have been struggling with this issue for a long time with no success. Hope anyone have seen this error before.
Link to the XDA forum thread: http://forum.xda-developers.com/nexus-6p/help/installing-multirom-huawei-nexus-6p-t3379860
Thanks in advance.

**Comment by npjohnson** [comment]
Report this on our Git @ github.com/multirom-nexus6p

But. Not a single other person has this problem with our latest release. After reporting it there, please close the issue here.

**Comment by npjohnson** [comment]
Appreciated.
