### ISSUE TITLE
Letting Multirom do not share kernel

### ISSUE THREAD

**Issue by GtrCraft** [Tasssadar/multirom#95]
How do you let multirom not sharing the kernel with secondary roms, or let secondary rom use their own boot.img/kernel? I am bringing up multirom for the Moto X Play and I can't boot CM as secondary rom because it uses the kernel from primary (Which is AOSP/CAF)

**Comment by npjohnson** [comment]
By default it doesn't share the kernel....

This is proven in MR TWRP when managing the secondary ROM it displays the option "Remove Boot IMG" showing that it is using a virtual boot imagem

**Comment by GtrCraft** [comment]
I see that option in my mr twrp. But it still uses the primary kernel on secondary roms.

**Comment by npjohnson** [comment]
Are you entirely sure? Run uname -a as root on both systems
